export const CONST = {
    loginApi: "/api/login",
    loginErr: "Login failed. Please check your account or Track ID.",
    networkErr: "Network error. Please try again later.",
    brandTitle: "TrackEase Express",
    brandSub: "Internal Tracking Console",
    heroTitle: "Log in to the TrackEase dashboard,<br />and track every <span>package in transit</span> in real time.",
    heroDesc: "Track the entire process from pickup to delivery at a glance. Support internal status updates and provide a tracking API for real-time user access.",
    timelineOrderSuccess: "Order Created",
    timelineSubOrderSuccess: "Order placed successfully. Tracking number TEX20... has been generated.",
    timelineOrderTransit: "In Transit",
    timelineSubOrderTransit: "The package is moving between sorting centers and mainline transportation.",
    timelineOrderDelivered: "Delivered",
    timelineSubOrderDelivered: "Delivery status is instantly synced to the frontend tracking page.",
    footNote: "Note: This page is for for the NYIT Course INCS 620 project demonstration.",
    disabled: "disabled",
    verifying: "Verifying...",
    loginDashboard: "Login",
    panelTitle: "Login",
    panelSub: "Log in with an internal account to create orders and update shipping milestones.",
    username: "Username",
    usernamePlaceholder: "Enter login username",
    password: "password",
    passwordPlaceholder: "Enter login password",
    trackId : "Tracking ID",
    trackIdPlaceholder: "e.g.TEX20...",
    styleAddr: "/component/login/trackLogin.css",
}