export const CONST = {
    summarySub: "The order shown is the one corresponding to the Track ID you just queried. You can enter a different Track ID on the login page to view other packages.",
    timelineTitle: "Delivery Progress (Diagram)",
    timelineOrderSuccess: "Order Created",
    timelineSubOrderSuccess: "Order placed successfully. The order has been recorded in the system.",
    timelineOrderTransit: "In Transit",
    timelineSubOrderTransit: "The package is in transit via the main line or transfer center.",
    timelineOrderDelivered: "Delivered",
    timelineSubOrderDelivered: "The status will update to “Delivered” after the package is signed for.",
    orderLs: "Order List",
    trackId: "Tracking ID",
    recipient: "Recipient",
    product: "Product",
    address: "Recipient Address",
    contact: "Contact Phone",
    status: "Status",
    orderErr: "Order parsing failed",
    brandTitle: "TrackEase Express",
    brandSub: "Internal Tracking Console",
    back: "← Back",
    styleAddr: "/component/dashboard/trackDashboard.css",
}